# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

services:

  rest-api:
    container_name: rest-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: always
    volumes:
      - ./src:/usr/src/app/src
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /usr/src/app/src
    networks:
      - service
    env_file:
      - .env

    depends_on:
      database:
        condition: service_healthy
  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    user: ${DB_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    networks:
      - service
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
volumes:
  db-data:
  db-logs:

networks:
  service:
    name: service
    driver: bridge
